---
#nofity调用该方法不生效 未解决
- name: restart mysql
  service: name=mariadb state=restarted

- name: enable mysql
  service: name=mariadb enabled=yes

- name: start zabbix server
  service: name=zabbix-server state=restarted

- name: http
  service: name=httpd state=restarted enabled=yes
