---
- name: disable selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: disable selinux
  command: setenforce 0 

- name: install rpm
  yum:
    name: 'http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm'
    state: installed

- name: install zabbix
  yum: name={{ item }} state=installed
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql 


- name: zabbix server
  template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf

- name: zabbix conf
  template: src=zabbix.conf dest=/etc/httpd/conf.d/zabbix.conf
  notify: 
  - start zabbix server
  - enable zabbix server

- name: open 80 
  firewalld: port=80/tcp zone=public permanent=true state=enabled immediate=yes
