---
- name: disable selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: disable selinux
  command: setenforce 0 

- name: install rpm
  yum:
    name: 'http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm'
    state: installed

- name: install zabbix agent
  yum: name={{ item }} state=installed
  with_items:
    - zabbix-agent


- name: zabbix server
  template: src=zabbix_agented.conf.j2 dest=/etc/zabbix/zabbix_agented.conf
  notify: 
  - start zabbix agent

- name: open 10050
  firewalld: port=10050/tcp zone=public permanent=true state=enabled immediate=yes
